languageCode = "en"
languageDirection = "ltr"
weight = 1

title = "Wendy Liga"
copyright = "&copy; 2025 Wendy Liga"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "A blog about technology, programming, and life."

[params.author]
  name = "Wendy Liga"
  image = "images/avatar.jpg"
  headline = "Your ordinary developer"
  bio = "I write about technology, programming, and life."
  links = [
    { email = "mailto:me@wendyliga.com" },
    { github = "https://github.com/wendyliga" },
    { x-twitter = "https://twitter.com/wendyliga" },
    { linkedin = "https://www.linkedin.com/in/wendy-liga/" }, 
  ]