[[main]]
  name = "About"
  pageRef = "about"
  weight = 9

  [[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "练习故事"
  pageRef = "chinese"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/wendyliga/wendyliga.com"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 40
  [main.params]
    action = "search"
    icon = "search"
    