[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "练习故事"
  pageRef = "chinese"
  weight = 30

[[main]]
  identifier = "search"
  weight = 40
  [main.params]
    action = "search"
    icon = "search"
    